[daemon]
AutomaticLoginEnable=True
AutomaticLogin=liveuser

[security]
DisallowTCP=true

[greeter]
Theme=org.freedesktop.colors-scripts.darker
IconTheme=Papirus-Dark
CursorTheme=breeze_cursors
CursorSize=24

[session]
Session=gnome-xorg