[LightDM]
logind-check-graphical=true
run-directory=/run/lightdm

[Seat:*]
greeter-session=lightdm-slick-greeter
user-session=cinnamon
autologin-user=liveuser
autologin-session=cinnamon
autologin-user-timeout=0
greeter-hide-users=false

[XDMCPServer]

[VNCServer]
