[Greeter]
background=/usr/share/archcosta/wallpapers/default.png
draw-user-backgrounds=true
draw-grid=false
show-hostname=true
show-power=true
show-keyboard=true
show-clock=true
show-quit=true
theme-name=Arc-Dark
icon-theme-name=Papirus-Dark
font-name=Noto Sans 11
xft-antialias=true
xft-dpi=96
xft-hintstyle=hintslight
xft-rgba=rgb
enable-hidpi=auto
