[greeter]
theme-name = Arc-Dark
icon-theme-name = Papirus-Dark
font-name = Noto Sans 11
background = /usr/share/archcosta/wallpapers/default.png
user-background = true
hide-user-image = false
default-user-image = /usr/share/archcosta/logo.png
xft-antialias = true
xft-dpi = 96
xft-hintstyle = hintslight
xft-rgba = rgb
indicators = ~host;~spacer;~clock;~spacer;~session;~language;~a11y;~power
clock-format = %a, %b %d  %H:%M
position = 50%,center 50%,center
screensaver-timeout = 300
panel-position = top
