[LightDM]
logind-check-graphical=true
run-directory=/run/lightdm

[Seat:*]
greeter-session=lightdm-gtk-greeter
user-session=xfce
autologin-user=liveuser
autologin-session=xfce
greeter-hide-users=false

[XDMCPServer]

[VNCServer]
