# ArchCosta mkinitcpio configuration for live ISO
MODULES=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)
BINARIES=()
FILES=()
HOOKS=(base udev plymouth modconf archiso archiso_loop_mnt block filesystems keyboard)
