[General]
InputMethod=
Numlock=on

[Theme]
Current=breeze
CursorTheme=breeze_cursors
CursorSize=24

[Users]
MaximumUid=60513
MinimumUid=1000
RememberLastSession=true
RememberLastUser=true

[Wayland]
SessionDir=/usr/share/wayland-sessions
SessionCommand=/usr/share/sddm/scripts/wayland-session

[X11]
SessionDir=/usr/share/xsessions
SessionCommand=/usr/share/sddm/scripts/Xsession
